services:
  octoprint_1:
    container_name: octoprint_1
    image: octoprint/octoprint:latest
    ports: [ "10000:80" ]
    volumes:
      - octo_data_1:/octoprint
    networks:
      - internal-network
    logging:
      driver: none

  octoprint_2:
    container_name: octoprint_2
    image: octoprint/octoprint:latest
    ports: [ "10001:80" ]
    volumes:
      - octo_data_2:/octoprint
    networks:
      - internal-network
    logging:
      driver: none

volumes:
  octo_data_1:
  octo_data_2:
